### ISSUE TITLE
$user->settings()->all() with defaults?

### ISSUE THREAD

**Issue by seeg0r** [Rudnev/laravel-settings#17]
Hi @Rudnev,

I have set up the User model as in the README:

`use Rudnev\Settings\Traits\HasSettings;
use Illuminate\Database\Eloquent\Model;

class User extends Model 
{
    use HasSettings;
    
    protected $settingsConfig = [
        'default' => [
            'timezone' => 'UTC'
        ]
    ];
    
    // ...
}`

I am also able to access the defaults like this:
`
$user->settings()->get('timezone');
`

But when I try to access all settings with
`
$user->settings()->all();
`
I just get the settings set up for this user manually, but not the configured defaults.

Is it possible to access all the configured defaults with all() somehow?

**Comment by Rudnev** [comment]
Hi @seeg0r,

I'm sorry for my delayed response. I released version 1.5.1, to get all model settings use the following methods:

```php
$user->settings->toArray();
```
or
```php
$user->settings->toJson();
```

Also use `$user->settings['timezone'];` instead of `$user->settings()->get('timezone');` because  the `settings()` method refer to persistent storage and ignores dirty (unsaved) state of the model.
